# <font color="red"> Data Science no Agronegócio</font>
## <span style="color:red">Linguagens e Ferramentas para *Data Science* no Agronegócio</span>

### <span style="color:darkred">Python: Numpy</span>

*Dr. Guilherme Martineli Sanches*<br>
*Cropman*

## Numpy 

Processamento vetorial/matricial:
- recursos para computação científica e álgebra linear

Outros pacotes dependem fortemente de `numpy`:
- `pandas`
- `matplotlib`
- `sklearn`

# Numpy Arrays

A estrutura de dados base, se assemelham às listas em Python, no entanto:
- Todo elemento em um array deve ser do mesmo tipo, tipicamente `float` ou `int`;
- Arrays viabilizam a realização eficiente de operações numéricas com grandes quantidades de dados, mais eficientes que listas;
- Cada dimensão de um array é chamada de eixo (_axis_)
- Eixos são numerados a partir de `0`
- Elementos acessados utilizando colchetes `[]`

### Construindo arrays

#### A partir de listas

Utilizando o construtor `numpy.array()`

#### Por métodos `numpy`:

`zeros`, `ones`,  `arange`,  `linspace`

In [2]:
# array com oito elementos iguais a zero
b1d = np.zeros((8))  
print('Zeros: ',b1d)

# array com dez elementos iguais a um
c1d = np.ones((10))  
print('Ones: ',c1d)

# array com numeros entre 1 e menor que 11, com passo 2 (similar a `range`)
d1d = np.arange(0,11,2)  
print('Range: ',d1d)

# array com 5 números igualmente espaçados no intervalo entre 1 e 2 
e1d = np.linspace(1,2,5) 
print('Linspace: ',e1d)

e1d2 = np.linspace(0,1,101) 
print('Linspace2: ',e1d2)

Zeros:  [0. 0. 0. 0. 0. 0. 0. 0.]
Ones:  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Range:  [ 0  2  4  6  8 10]
Linspace:  [1.   1.25 1.5  1.75 2.  ]
Linspace2:  [0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13
 0.14 0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27
 0.28 0.29 0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4  0.41
 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55
 0.56 0.57 0.58 0.59 0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69
 0.7  0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8  0.81 0.82 0.83
 0.84 0.85 0.86 0.87 0.88 0.89 0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97
 0.98 0.99 1.  ]


#### Arrays multidimensionais

In [3]:
a2d = np.array([[1,3,5,7,9,11],
                [2,4,6,8,10,12],
                [0,1,2,3,4,5]]  )
print('a2d=\n',a2d)

a2d=
 [[ 1  3  5  7  9 11]
 [ 2  4  6  8 10 12]
 [ 0  1  2  3  4  5]]


In [5]:
#matriz 5X3 de zeros
b2d = np.zeros((5,3))  
print('Zeros 2d: \n',b2d)

# criando matriz 4X8 de 1s
c2d = np.ones((4,8))
print('Ones 2d:\n',c2d)

# criando matrix identidade 3X3
d2d = np.identity(5) 
print('Identity: \n',d2d)

Zeros 2d: 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones 2d:
 [[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]
Identity: 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Arrays são objetos _ndarrays_ 

Seus atributos são: 
- `ndarray.ndim`: número de eixos (dimensões) do array
- `ndarray.shape`: uma tupla de inteiros indicando o tamanho do array em cada dimensão
- `ndarray.size`:  o número total de elementos do array
- `ndarray.dtype`: tipo dos elementos no array
- `ndarray.itemsize`: o tamanho em bytes de cada elemento do array
- `ndarray.T`: versão transposta do array

In [6]:
print(a1d)
print(c2d)

[ 1  3  5  7 13]
[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


In [7]:
print(" ndim: numero de eixos dos arrays")
print('a1d.ndim =',a1d.ndim)
print('c2d.ndim =',c2d.ndim)

 ndim: numero de eixos dos arrays
a1d.ndim = 1
c2d.ndim = 2


In [8]:
print("\n shape: tamanho do array em cada dimensao")
print('a1d.shape =',a1d.shape)
print('b1d.shape =',b1d.shape)
print('a2d.shape =',a2d.shape)
print('c2d.shape =',c2d.shape)


 shape: tamanho do array em cada dimensao
a1d.shape = (5,)
b1d.shape = (8,)
a2d.shape = (3, 6)
c2d.shape = (4, 8)


In [9]:
print("\n size: numero total de elementos")
print('a1d.size =',a1d.size)
print('b1d.size =',b1d.size)
print('a2d.size =',a2d.size)
print('c2d.size =',c2d.size)


 size: numero total de elementos
a1d.size = 5
b1d.size = 8
a2d.size = 18
c2d.size = 32


In [10]:
print("\n dtype: tipo dos elementos")
print('a1d.dtype =',a1d.dtype)
print('b1d.dtype =',b1d.dtype)
print('a2d.dtype =',a2d.dtype)
print('c2d.dtype =',c2d.dtype)


 dtype: tipo dos elementos
a1d.dtype = int64
b1d.dtype = float64
a2d.dtype = int64
c2d.dtype = float64


In [11]:
print("\n itemsize: tamanho em bytes de cada elemento")
print('a1d.itemsize =',a1d.itemsize)
print('b1d.itemsize =',b1d.itemsize)
print('a2d.itemsize =',a2d.itemsize)
print('c2d.itemsize =',c2d.itemsize)


 itemsize: tamanho em bytes de cada elemento
a1d.itemsize = 8
b1d.itemsize = 8
a2d.itemsize = 8
c2d.itemsize = 8
